language: php

php:
  - 5.6

before_install:
  - php /home/travis/.phpenv/versions/5.6/bin/composer self-update

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

script: phpunit tests/
